# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "im_logger"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = "2013-12-05"
  s.description = "immat\u{e9}riel.fr logger lib"
  s.email = "jboulnois@immateriel.fr"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/im_logger.rb"
  ]
  s.homepage = "http://github.com/immateriel/im_logger"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "immat\u{e9}riel.fr logger lib"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

